source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0’
use_frameworks!

target 'letusintroduceyou' do
    pod 'Alamofire', '~> 4.4'
    pod 'SDWebImage', '~>3.8'
    pod 'SwiftyJSON'
    pod 'Cosmos', '~> 11.0'
    pod 'Floaty', '~> 3.0.0'
    pod 'JVFloatLabeledTextField'
    pod 'DropDown'
    pod 'BSImagePicker', '~> 2.4'
    pod 'UICircularProgressRing'
end
